# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'myappimage'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
         '$(imageName):$(Build.BuildId)'
    - script: |
        docker save $(imageName):$(Build.BuildId) -o $(Build.ArtifactStagingDirectory)/$(imageName).tar
      displayName: Save Docker Image to tar
    - publish: $(Build.ArtifactStagingDirectory)/$(imageName).tar
      artifact: dockerimagetarfile